---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tracing-server
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: tracing
  labels:
    app.kubernetes.io/name: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tracing-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: "openzipkin/zipkin:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: tracing-server
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.tracing.svc.cluster.local:9411/api/v2/spans"
          resources:
            {}