---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | default "default"}}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile | quote }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ .Values.serviceName }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.tracing.svc.cluster.local:9411/api/v2/spans"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if and .Values.volumeMounts .Values.volumeMounts.mountConfigMap }}
          volumeMounts:
            - name: config-map
              mountPath: {{ .Values.volumeMounts.configMountPath }}
              subPath: {{ .Values.volumeMounts.configSubPath }}
          {{- end}}
      {{- if and .Values.volumeMounts .Values.volumeMounts.mountConfigMap}}
      volumes:
        - name: config-map
          configMap:
            name: {{ .Values.configMap.name }}
      {{- end}} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "default"}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}