{{- if and .Values.configMap .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.configMap.name }}
data:
{{ toYaml .Values.configMap.data | indent 2 }}
{{- end }}