nameOverride: prometheus
serviceName: prometheus
namespace: monitoring

replicaCount: 1

image:
  repository: hongphuchcmus/spring-petclinic-prometheus
  tag: latest
  pullPolicy: Always

containerPort: 9090
springProfile: docker

service:
  type: ClusterIP
  port: 9090

resources: {}