nameOverride: api-gateway
serviceName: api-gateway

replicaCount: 1

image:
  repository: hongphuchcmus/spring-petclinic-api-gateway
  tag: latest
  pullPolicy: Always

containerPort: 8080
springProfile: docker

service:
  type: NodePort
  port: 8080
  nodePort: 30200

resources: {}

ingress:
  enabled: true
  name: "api-gateway-ingress"
  className: "nginx"
  host: "spring-petclinic.com"
  tls: false
  tlsSecret: ""
