groups:
  - name: http-alerts-error-requests
    rules:
      - alert: TooManyServerErrors
        expr: increase(http_server_requests_seconds_count{status=~"[45].."}[30s]) > 10
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Too many server errors"
          description: "More than 1 HTTP 5xx errors in the last 30 seconds."